Draft: add api for setting visibility of crop margins, render crop margins as boxes
rdiankov/openrave pull request #1242
Opened 2023-06-02 05:29 UTC by seanzhang15

2023-06-05 08:15 UTC, braineo requested changes

2023-06-05 08:15 UTC, braineo commented on plugins/qtosgrave/qtosgviewer.cpp
> +    _posgWidget->GetItemFromName(bodyName)->SetCropMarginVisible(linkName, geometryName, cropContainerType, visible);
check for nullptr

2023-06-05 08:15 UTC, braineo commented on plugins/qtosgrave/osgrenderitem.cpp
> +                            orgeom->GetPositiveCropContainerMargins(),
let's remove the trailing whitespace

2023-06-06 00:31 UTC, braineo approved these changes

2023-06-12 01:14 UTC, seanzhang15 commented
closing in favor of https://github.com/rdiankov/openrave/pull/1251

2023-06-12 01:14 UTC, closed without merging

2023-06-12 01:16 UTC, cielavenir commented
so you switched to rdiankov:crop-margins rather than your fork, thanks @seanzhang15